@echo off
setlocal EnableDelayedExpansion

echo === claude_executor installer ===
echo.

where python >nul 2>nul
if errorlevel 1 (
  echo [error] python not found on PATH. Install Python 3.11+ first.
  exit /b 1
)

where claude >nul 2>nul
if errorlevel 1 (
  echo [warn]  claude CLI not found on PATH.
  echo         The executor still starts but run.start commands will fail
  echo         until claude is installed: npm install -g @anthropic-ai/claude-code
  echo.
)

set "ROOT=%~dp0"
if "%ROOT:~-1%"=="\" set "ROOT=%ROOT:~0,-1%"
set "ENV_PATH=%ROOT%\.env"

if exist "%ENV_PATH%" (
  echo .env already exists at %ENV_PATH% — keeping existing config.
  goto :register
)

echo --- bridge config ---
set /p BRIDGE_URL="Bridge base URL (e.g. https://semirainnas.tailb6e1a3.ts.net): "
set /p BRIDGE_TOKEN="Bridge bearer token: "

set "MACHINE_ID=%COMPUTERNAME%"
set /p USER_MACHINE_ID="Machine id [%MACHINE_ID%]: "
if not "%USER_MACHINE_ID%"=="" set "MACHINE_ID=%USER_MACHINE_ID%"

> "%ENV_PATH%" (
  echo # claude_executor — generated by install.bat
  echo CLAUDE_BRIDGE_URL=!BRIDGE_URL!
  echo CLAUDE_BRIDGE_TOKEN=!BRIDGE_TOKEN!
  echo CLAUDE_BRIDGE_MACHINE_ID=!MACHINE_ID!
)
echo Wrote %ENV_PATH%

:register
echo.
echo --- next steps ---
echo  1. Test once:    %ROOT%\start.bat
echo  2. To autostart on login, run as administrator:
echo      schtasks /create /sc onlogon /tn "ClaudeExecutor" /tr "%ROOT%\start.bat"
echo     (or set up a Task Scheduler entry pointing to start.bat manually)
echo.
endlocal
